set script_dir [file normalize [file dirname [info script]]]
set fpga_dir [file dirname $script_dir]
set repo_dir [file dirname $fpga_dir]
set project_dir [file join $script_dir build gt_idle_tx]
set artifact_name gt_idle_tx
set gtx_tx_mask 15
set sfp_tx_enable_mask 15

# With no argument, build the normal all-four-lane image.  An optional lane
# number (0..3) creates a one-hot cage-identification image without changing
# any GTX electrical or PCS parameters.
if {[llength $argv] == 1} {
    set selected_lane [lindex $argv 0]
    if {![string is integer -strict $selected_lane] ||
            $selected_lane < 0 || $selected_lane > 3} {
        error "Lane selector must be an integer from 0 through 3"
    }
    set gtx_tx_mask [expr {1 << $selected_lane}]
    set sfp_tx_enable_mask $gtx_tx_mask
    set artifact_name gt_idle_tx_lane${selected_lane}
    set project_dir [file join $script_dir build $artifact_name]
} elseif {[llength $argv] == 2} {
    set selector [lindex $argv 0]
    set selected_lane [lindex $argv 1]
    if {![string is integer -strict $selected_lane] ||
            $selected_lane < 0 || $selected_lane > 3} {
        error "Lane selector must be an integer from 0 through 3"
    }
    set one_hot_mask [expr {1 << $selected_lane}]
    if {$selector eq "gtx"} {
        set gtx_tx_mask $one_hot_mask
        set artifact_name gt_idle_gtx${selected_lane}
    } elseif {$selector eq "enable"} {
        set sfp_tx_enable_mask $one_hot_mask
        set artifact_name gt_idle_enable${selected_lane}
    } else {
        error "Two-argument selector must be gtx or enable"
    }
    set project_dir [file join $script_dir build $artifact_name]
} elseif {[llength $argv] != 0} {
    error "Usage: build_gt_idle_tx.tcl ?lane_0_to_3 | gtx|enable lane?"
}

# Reuse only the unencrypted, primitive-level GTXE2 wrappers generated by the
# diagnostic IP project.  Deliberately do not add the time-limited MAC/PCS IP.
set gt_dir [file join $script_dir build uart_10g_probe uart_10g_probe.gen \
    sources_1 ip eth10g_master bd_0 ip ip_1 synth]
set gt_sources [list \
    [file join $gt_dir bd_1a40_xpcs_0_ff_synchronizer_rst.v] \
    [file join $gt_dir bd_1a40_xpcs_0_shared_clock_and_reset.v] \
    [file join $gt_dir bd_1a40_xpcs_0_gt_common.v] \
    [file join $gt_dir bd_1a40_xpcs_0_gtwizard_10gbaser_gt.v] \
    [file join $gt_dir bd_1a40_xpcs_0_gtwizard_10gbaser_multi_gt.v]]
foreach source $gt_sources {
    if {![file exists $source]} {
        error "Missing generated GTX wrapper: $source; run build_uart_10g_probe.tcl once"
    }
}

create_project -force gt_idle_tx $project_dir -part xc7k325tffg676-3
set_property target_language Verilog [current_project]
add_files -norecurse [concat $gt_sources [list \
    [file join $repo_dir rtl generated Predef_pkg.sv] \
    [file join $repo_dir rtl generated UARTProbe.sv] \
    [file join $repo_dir rtl generated UARTProbeMemory.sv] \
    [file join $fpga_dir rtl uart_banner_tx.sv] \
    [file join $script_dir sfp_i2c_diag.sv] \
    [file join $script_dir scrambler_parallel.sv] \
    [file join $script_dir gt_idle_64b66b.sv] \
    [file join $script_dir gt_rx_header_checker.sv] \
    [file join $script_dir gt_idle_tx_top.sv]]]
add_files -fileset constrs_1 -norecurse [file join $script_dir gt_idle_tx.xdc]
set_property top gt_idle_tx_top [current_fileset]
set_property generic [list GTX_TX_MASK=$gtx_tx_mask \
    SFP_TX_ENABLE_MASK=$sfp_tx_enable_mask] [current_fileset]
update_compile_order -fileset sources_1

set_property strategy Flow_RuntimeOptimized [get_runs synth_1]
set_property strategy Performance_Explore [get_runs impl_1]
set_property STEPS.PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]
set_property STEPS.WRITE_BITSTREAM.ARGS.BIN_FILE true [get_runs impl_1]

launch_runs impl_1 -to_step write_bitstream -jobs 1
wait_on_run impl_1
if {[get_property STATUS [get_runs impl_1]] ne "write_bitstream Complete!"} {
    error "GT idle TX implementation failed: [get_property STATUS [get_runs impl_1]]"
}

set run_dir [get_property DIRECTORY [get_runs impl_1]]
foreach extension {bit bin} {
    set source [file join $run_dir gt_idle_tx_top.$extension]
    set destination [file join $script_dir $artifact_name.$extension]
    file copy -force $source $destination
    puts "GT_IDLE_TX_ARTIFACT=$destination"
}
